### ISSUE TITLE
Nuget Version is outdated

### ISSUE THREAD

**Issue by UkeHa** [eBay/ebay-oauth-csharp-client#33]
The latest package hasn't been updated on nuget, please upload the latest release so that nuget is able to fetch the latest release. @sdhiman30  / @LokeshRishi 

![grafik](https://github.com/eBay/ebay-oauth-csharp-client/assets/2254304/86abed3b-9702-4bbc-8cbd-181d18d69121)

![grafik](https://github.com/eBay/ebay-oauth-csharp-client/assets/2254304/1e3b47c2-00e2-4d7e-b911-5e347376c775)

**Comment by LokeshRishi** [comment]
@UkeHa Thank you for reporting this. We have published the 2.0.0 package: https://www.nuget.org/packages/eBay.OAuth.Client/2.0.0
