### ISSUE TITLE
Exception When Getting Application Token

### ISSUE THREAD

**Issue by pjones19832023** [eBay/ebay-oauth-csharp-client#47]
When i Get the application Token i get this error

System.MissingMethodException: 'Method not found: 'RestSharp.RestResponse RestSharp.RestClientExtensions.Execute(RestSharp.RestClient, RestSharp.RestRequest, System.Threading.CancellationToken)'.'

see code below

 CredentialUtil.Load("<Path to File>\\ebay-config-sample.yaml");
 List<String> scopes = new List<String>();
 RestClient restClient = new RestClient();
          
 scopes.Add("https://api.ebay.com/oauth/api_scope");
 scopes.Add("https://api.ebay.com/oauth/api_scope/sell.inventory");
 oAuth2 = new OAuth2Api();
 
  var result = oAuth2.GetApplicationToken(OAuthEnvironment.SANDBOX, scopes).AccessToken.Token;

furthur investigation shows an issue with this section for AppTokenCache method fetch token see below:

 private OAuthResponse FetchToken(OAuthEnvironment environment, string requestPayload, TokenType tokenType)
 {
     CredentialUtil.Credentials credentials = GetCredentials(environment);
     RestClient restClient = new RestClient(environment.ApiEndpoint());
     RestRequest restRequest = new RestRequest
     {
         Method = Method.Post
     };
     restRequest.AddHeader(Constants.HEADER_AUTHORIZATION, OAuth2Util.CreateAuthorizationHeader(credentials));
     restRequest.AddParameter(Constants.HEADER_CONTENT_TYPE, requestPayload, ParameterType.RequestBody);
     RestResponse response = RestClientExtensions.Execute(restClient, restRequest, default(CancellationToken));
     return HandleApiResponse(response, tokenType);
 }

 RestClientExtensions.Execute(restClient, restRequest, default(CancellationToken)); has no method that takes a cancellation token. The ExecuteAsync does but not the non synchronous.

**Comment by pjones19832023** [comment]
Just to add I recreated the class and altered RestClientExtensions.Execute() the system now works correctly.

**Comment by abem-fb** [comment]
@sdhiman30 @LokeshRishi 
Is there any plan to release dev version in prod with RestSharp v112?
for eBay.OAuth.Client nuget package current version 2.0.2 still throws this error

**Comment by LokeshRishi** [comment]
@pjones19832023 @abem-fb I have published version [2.0.3](https://www.nuget.org/packages/eBay.OAuth.Client/2.0.3) of the eBay.OAuth.Client nuget package that should fix the issue with RestSharp. 

Please update to the latest version and let me know if you encounter any further issues.

**Comment by LokeshRishi** [comment]
Fixed in version [2.0.3](https://github.com/eBay/ebay-oauth-csharp-client/pull/48)
